# Generated by Django 3.1.4 on 2020-12-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='slider.png', upload_to='slider')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('f', 'face'), ('b', 'back')], max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
