# Generated by Django 3.1.3 on 2020-12-22 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProCat',
            fields=[
                ('cat_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pic', models.ImageField(default='cat.png', upload_to='pro_cot')),
                ('name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('pro_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='pro.jpg', upload_to='product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.masterprocat')),
            ],
        ),
    ]
